/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "secondary-container": "#4967f4",
        "on-secondary-fixed-variant": "#0031c4",
        "primary-container": "#176774",
        "on-secondary-fixed": "#001159",
        "primary-fixed": "#a8eefd",
        "tertiary-fixed-dim": "#95d4b3",
        "secondary": "#2b4cda",
        "inverse-on-surface": "#f0f1f2",
        "primary-fixed-dim": "#8cd1e0",
        "primary": "#004e59",
        "surface-container": "#edeeef",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "outline-variant": "#bec8cb",
        "surface-variant": "#e1e3e4",
        "surface-container-highest": "#e1e3e4",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface": "#191c1d",
        "surface-tint": "#196775",
        "secondary-fixed": "#dee1ff",
        "on-background": "#191c1d",
        "on-primary-fixed": "#001f25",
        "on-primary": "#ffffff",
        "surface": "#f8f9fa",
        "tertiary-fixed": "#b1f0ce",
        "tertiary-container": "#2b684d",
        "on-tertiary-fixed": "#002114",
        "on-tertiary-fixed-variant": "#0e5138",
        "inverse-primary": "#8cd1e0",
        "on-primary-container": "#9de2f1",
        "tertiary": "#0c5037",
        "secondary-fixed-dim": "#bac3ff",
        "surface-container-low": "#f3f4f5",
        "on-surface-variant": "#3f484b",
        "inverse-surface": "#2e3132",
        "surface-container-high": "#e7e8e9",
        "surface-dim": "#d9dadb",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9fa",
        "background": "#f8f9fa",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#004e5a",
        "on-tertiary-container": "#a5e4c3",
        "on-secondary-container": "#fffbff",
        "outline": "#6f797c"
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
}
