import os
from pymongo import MongoClient
from dotenv import load_dotenv

load_dotenv()

def seed_passages():
    mongo_uri = os.getenv("MONGO_URI")
    if not mongo_uri:
        print("Error: MONGO_URI environment variable not set.")
        return

    client = MongoClient(mongo_uri)
    # Extract database name from URI or default to 'akshara'
    db_name = mongo_uri.split("/")[-1].split("?")[0] or "akshara"
    db = client[db_name]
    passages_col = db.passages

    passages = [
        # Level A1 - Lexile 200
        {"title": "The Sleepy Black Cat", "text": "The cat is on the mat. It is a big, black cat. The cat likes to sleep.", "cefr_level": "A1", "lexile_score": 200, "category": "Literature"},
        {"title": "Sam's Red Book", "text": "My name is Sam. I have a red book. I read my book every night.", "cefr_level": "A1", "lexile_score": 200, "category": "Literature"},
        {"title": "A Sunny Day at the Park", "text": "The sun is hot today. The flowers are red and blue. I like the park.", "cefr_level": "A1", "lexile_score": 200, "category": "Literature"},
        {"title": "The Properties of Water", "text": "Water is cold. Ice is frozen water. We drink water every day.", "cefr_level": "A1", "lexile_score": 200, "category": "Science"},
        {"title": "How Plants Grow", "text": "Plants need sun. Plants need water to grow. They are green.", "cefr_level": "A1", "lexile_score": 200, "category": "Science"},
        {"title": "The Bright Round Moon", "text": "The moon is in the sky. It is white and round. It shines at night.", "cefr_level": "A1", "lexile_score": 200, "category": "Science"},
        {"title": "Life in Ancient Times", "text": "Long ago, people lived in tents. They ate fruit and meat. Life was hard.", "cefr_level": "A1", "lexile_score": 200, "category": "History"},
        {"title": "The Mighty Stone Castles", "text": "Kings lived in big castles. The castles were made of stone.", "cefr_level": "A1", "lexile_score": 200, "category": "History"},
        {"title": "The Old River Map", "text": "This is an old map. It shows a small town. The town is near a river.", "cefr_level": "A1", "lexile_score": 200, "category": "History"},
        {"title": "Snow Day Announcement", "text": "The school is closed today. There is a lot of snow. Stay home.", "cefr_level": "A1", "lexile_score": 200, "category": "News"},
        {"title": "The New Playground", "text": "A new park is open. It has a big playground for all the children.", "cefr_level": "A1", "lexile_score": 200, "category": "News"},
        {"title": "Daily Bread Sale", "text": "The shop has a sale. Bread is cheap today. Many people are there.", "cefr_level": "A1", "lexile_score": 200, "category": "News"},

        # Level A2 - Lexile 450
        {"title": "Searching for a Friend", "text": "The young boy walked to the forest because he wanted to find his dog. He called its name loudly, but it did not come back.", "cefr_level": "A2", "lexile_score": 450, "category": "Literature"},
        {"title": "The Dark Quiet Room", "text": "She opened the old door slowly. Inside the room, there was a small wooden table and a chair. It was very dark and quiet.", "cefr_level": "A2", "lexile_score": 450, "category": "Literature"},
        {"title": "Grandfather's Magic Stories", "text": "Every Sunday, my grandfather tells me a story. His stories are always about magic animals and brave heroes who save the day.", "cefr_level": "A2", "lexile_score": 450, "category": "Literature"},
        {"title": "The Seasons of Earth", "text": "The Earth goes around the sun. It takes one year to finish the circle. This is why we have different seasons like summer and winter.", "cefr_level": "A2", "lexile_score": 450, "category": "Science"},
        {"title": "The Life of Birds", "text": "Birds have feathers to keep them warm. They also use their feathers to fly high in the sky. Most birds build nests for their eggs.", "cefr_level": "A2", "lexile_score": 450, "category": "Science"},
        {"title": "The Power of Magnets", "text": "Magnets can pull some metals. If you put a magnet near a piece of iron, it will stick to it. This is called magnetic force.", "cefr_level": "A2", "lexile_score": 450, "category": "Science"},
        {"title": "Roman Engineering", "text": "The Romans built many long roads. They used stones to make the roads strong. Some of these old roads are still here today.", "cefr_level": "A2", "lexile_score": 450, "category": "History"},
        {"title": "The First Flight", "text": "The Wright brothers made the first airplane. It did not fly very far or very high, but it changed how people travel forever.", "cefr_level": "A2", "lexile_score": 450, "category": "History"},
        {"title": "Life Before Electricity", "text": "In the past, people did not have electricity. They used candles for light at night, and they washed their clothes by hand in the river.", "cefr_level": "A2", "lexile_score": 450, "category": "History"},
        {"title": "Local Team Victory", "text": "A local team won the big football match yesterday. Thousands of fans cheered in the stadium. The players were very happy with the result.", "cefr_level": "A2", "lexile_score": 450, "category": "News"},
        {"title": "City Center Flood", "text": "Heavy rain caused a small flood in the city center. Police are asking drivers to take different roads until the water goes down.", "cefr_level": "A2", "lexile_score": 450, "category": "News"},
        {"title": "A New Modern Hospital", "text": "The city will build a new hospital next year. It will have modern beds and doctors from all over the country to help sick people.", "cefr_level": "A2", "lexile_score": 450, "category": "News"},

        # Level B1 - Lexile 750
        {"title": "Maria's Departure", "text": "As the train left the station, Maria looked out the window and sighed. She was leaving her hometown for the first time, feeling a mixture of excitement and sadness about the journey ahead.", "cefr_level": "B1", "lexile_score": 750, "category": "Literature"},
        {"title": "The Detective's Discovery", "text": "The detective found a hidden letter inside the old book. It contained a secret code that he needed to understand. He knew this was the clue he had been searching for all week.", "cefr_level": "B1", "lexile_score": 750, "category": "Literature"},
        {"title": "The Secret of the Lake", "text": "The village was known for its beautiful lake. Legends said that a monster lived at the bottom, but the locals knew it was just a story invented to keep children away from the deep water.", "cefr_level": "B1", "lexile_score": 750, "category": "Literature"},
        {"title": "The Process of Photosynthesis", "text": "Photosynthesis is a process used by plants to make their own food. They take in sunlight, water, and carbon dioxide from the air, and turn them into oxygen and energy to help them grow.", "cefr_level": "B1", "lexile_score": 750, "category": "Science"},
        {"title": "The Force of Gravity", "text": "Gravity is an invisible force that pulls objects toward each other. It is the reason why our feet stay firmly on the ground, and it is also what keeps the moon in orbit around the Earth.", "cefr_level": "B1", "lexile_score": 750, "category": "Science"},
        {"title": "The Importance of Recycling", "text": "Recycling is important for protecting the environment. When we recycle paper, plastic, and glass, we reduce the amount of waste in landfills and save natural resources for future generations.", "cefr_level": "B1", "lexile_score": 750, "category": "Science"},
        {"title": "The Industrial Revolution", "text": "The Industrial Revolution completely changed how goods were produced. Instead of making things by hand at home, people began working in large factories using machines powered by steam and coal.", "cefr_level": "B1", "lexile_score": 750, "category": "History"},
        {"title": "The California Gold Rush", "text": "The discovery of gold in California in 1848 brought thousands of people to the area. They left their families behind, hoping to find wealth, but only a few actually became rich.", "cefr_level": "B1", "lexile_score": 750, "category": "History"},
        {"title": "The Invention of the Printing Press", "text": "The printing press was invented in the 15th century. Before this invention, books had to be copied by hand, which made them very expensive. The press allowed information to spread quickly across Europe.", "cefr_level": "B1", "lexile_score": 750, "category": "History"},
        {"title": "Sleep and Student Success", "text": "A recent study shows that a lack of sleep can affect a student's performance in school. Doctors recommend that teenagers get at least eight hours of rest every night to improve their memory and focus.", "cefr_level": "B1", "lexile_score": 750, "category": "News"},
        {"title": "Clean Air Initiative", "text": "The government has announced a new plan to reduce air pollution in the capital. Over the next five years, they will plant more trees and increase taxes on cars that produce too much exhaust.", "cefr_level": "B1", "lexile_score": 750, "category": "News"},
        {"title": "Summer Music Festival", "text": "Thousands of music fans gathered in the park this weekend for the annual summer festival. Despite a brief rain shower on Saturday afternoon, the event was a huge success, featuring bands from around the world.", "cefr_level": "B1", "lexile_score": 750, "category": "News"},

        # Level B2 - Lexile 950
        {"title": "The Dilapidated Mansion", "text": "The dilapidated mansion, which had stood empty for decades, was finally being renovated. Eleanor watched the workers from afar, wondering if the restoration would erase the lingering ghosts of her family's troubled past or merely paint over them.", "cefr_level": "B2", "lexile_score": 950, "category": "Literature"},
        {"title": "The Mountaineer's Ambition", "text": "Despite his exhaustion, the mountaineer pushed forward, his breath visible in the freezing air. Reaching the summit had been a lifelong ambition, and he refused to let the sudden, blinding snowstorm dictate the outcome of his journey.", "cefr_level": "B2", "lexile_score": 950, "category": "Literature"},
        {"title": "Psychological Tension in Art", "text": "The author's latest novel has been praised for its complex character development. Unlike his previous works, which relied heavily on fast-paced action, this narrative deliberately explores the psychological tension between two rival artists living in Paris.", "cefr_level": "B2", "lexile_score": 950, "category": "Literature"},
        {"title": "The Human Immune System", "text": "The human immune system is a highly complex network of cells and proteins that defends the body against infection. When a foreign pathogen enters, the system immediately recognizes it and produces specific antibodies to neutralize the threat before it spreads.", "cefr_level": "B2", "lexile_score": 950, "category": "Science"},
        {"title": "The Vitality of Renewable Energy", "text": "Renewable energy sources, such as wind and solar power, are becoming increasingly vital as the effects of climate change worsen. Transitioning away from fossil fuels requires significant technological innovation and global cooperation to stabilize greenhouse gas emissions.", "cefr_level": "B2", "lexile_score": 950, "category": "Science"},
        {"title": "The Debate Over Genetic Modification", "text": "Genetic modification in agriculture has sparked intense debate among scientists and consumers. While proponents argue that genetically engineered crops offer higher yields and resistance to pests, critics raise valid concerns regarding long-term ecological impacts and biodiversity loss.", "cefr_level": "B2", "lexile_score": 950, "category": "Science"},
        {"title": "The Cultural Rebirth of the Renaissance", "text": "The Renaissance was a period of profound cultural and intellectual rebirth that swept through Europe following the Middle Ages. Characterized by a renewed interest in classical antiquity, it produced some of the world's most enduring artistic masterpieces and scientific discoveries.", "cefr_level": "B2", "lexile_score": 950, "category": "History"},
        {"title": "The Engineering of the Panama Canal", "text": "The construction of the Panama Canal was an unprecedented engineering feat that drastically reduced shipping times between the Atlantic and Pacific oceans. However, the project was plagued by severe challenges, including harsh jungle terrain and deadly outbreaks of malaria and yellow fever.", "cefr_level": "B2", "lexile_score": 950, "category": "History"},
        {"title": "Geopolitical Tension in the Cold War", "text": "The Cold War was an era of geopolitical tension primarily between the United States and the Soviet Union. Although it never escalated into direct military conflict, the ideological rivalry manifested in arms races, proxy wars, and the historic Space Race.", "cefr_level": "B2", "lexile_score": 950, "category": "History"},
        {"title": "Volatility in Global Markets", "text": "Global stock markets experienced significant volatility today following unexpected shifts in international trade policies. Economists warn that if these aggressive tariffs remain in place, consumer prices could rise sharply, potentially triggering a mild recession by the end of the fiscal year.", "cefr_level": "B2", "lexile_score": 950, "category": "News"},
        {"title": "Ancient Tomb Discovery in Egypt", "text": "A groundbreaking archaeological discovery was made in Egypt yesterday, where researchers unearthed a previously unknown tomb dating back to the New Kingdom. The site contains remarkably preserved artifacts that are expected to shed new light on ancient burial rituals.", "cefr_level": "B2", "lexile_score": 950, "category": "News"},
        {"title": "Protests for Environmental Accountability", "text": "Environmental activists organized a massive protest outside the multinational corporation's headquarters. They are demanding immediate corporate accountability regarding the recent oil spill, which has devastated local marine ecosystems and heavily impacted the coastal fishing industry.", "cefr_level": "B2", "lexile_score": 950, "category": "News"},

        # Level C1 - Lexile 1150
        {"title": "Existential Dread and Cynicism", "text": "The protagonist's existential dread is palpable throughout the narrative, manifesting not as explosive outbursts, but as a quiet, corrosive cynicism. The author masterfully employs stream-of-consciousness techniques to plunge the reader into a fractured psyche, leaving the boundary between stark reality and feverish hallucination deliberately ambiguous.", "cefr_level": "C1", "lexile_score": 1150, "category": "Literature"},
        {"title": "The Paralyzing Force of Nostalgia", "text": "Nostalgia permeates the novel, functioning less as a comforting sentiment and more as a paralyzing force. The characters find themselves perpetually tethered to a romanticized past, rendering them inherently incapable of navigating the turbulent socio-political landscape of the present day without experiencing profound disillusionment.", "cefr_level": "C1", "lexile_score": 1150, "category": "Literature"},
        {"title": "A Tapestry of Sensory Details", "text": "Her prose is an intricate tapestry of sensory details, devoid of superfluous ornamentation. By stripping away conventional dialogue tags and employing a fragmented chronological structure, she demands active participation from the reader, forcing them to piece together the tragic tapestry of the protagonist's demise.", "cefr_level": "C1", "lexile_score": 1150, "category": "Literature"},
        {"title": "Paradigm Shifts in Quantum Computing", "text": "Quantum computing represents a paradigm shift in processing capabilities, leveraging the principles of superposition and entanglement. Unlike classical bits, which are binary, qubits can exist in multiple states simultaneously, theoretically enabling the resolution of cryptographic and molecular modeling problems currently deemed computationally intractable.", "cefr_level": "C1", "lexile_score": 1150, "category": "Science"},
        {"title": "The Neuroplasticity of the Adult Brain", "text": "The neuroplasticity of the adult brain continually confounds earlier neurological dogmas, which posited that neural pathways were rigid post-adolescence. Current neuroimaging studies unequivocally demonstrate that sustained cognitive behavioral therapies can structurally rewire synaptic connections, offering unprecedented therapeutic avenues for neurodegenerative disorders.", "cefr_level": "C1", "lexile_score": 1150, "category": "Science"},
        {"title": "Epigenetics and Gene Expression", "text": "Epigenetics fundamentally alters our comprehension of heredity, illustrating that environmental factors can influence gene expression without altering the underlying DNA sequence. This dynamic mechanism explains how variables such as chronic stress or nutritional deficits can trigger phenotypic modifications that are occasionally inheritable by subsequent generations.", "cefr_level": "C1", "lexile_score": 1150, "category": "Science"},
        {"title": "The Fragmentation of the Roman Empire", "text": "The dissolution of the Roman Empire was not a singular, cataclysmic event, but rather a protracted process of fragmentation exacerbated by economic inflation, bureaucratic bloat, and unrelenting external pressures. Historiographical consensus now leans toward viewing this epoch as a complex transition into late antiquity rather than a precipitous fall into dark ages.", "cefr_level": "C1", "lexile_score": 1150, "category": "History"},
        {"title": "Punitive Diplomacy and the Treaty of Versailles", "text": "The Treaty of Versailles is frequently cited by contemporary historians as a quintessential example of punitive diplomacy. The draconian reparations imposed upon the vanquished nations not only crippled their post-war economies but invariably cultivated a fertile breeding ground for the virulent nationalism that precipitated subsequent global conflicts.", "cefr_level": "C1", "lexile_score": 1150, "category": "History"},
        {"title": "Modernization in Meiji Japan", "text": "The Meiji Restoration catalyzed an era of breakneck modernization in Japan, systematically dismantling the centuries-old feudal shogunate. By aggressively assimilating Western industrial technologies and adopting a centralized bureaucratic apparatus, the island nation rapidly transformed itself into a formidable imperial power on the global stage.", "cefr_level": "C1", "lexile_score": 1150, "category": "History"},
        {"title": "Seismic Shifts in Geopolitics", "text": "The geopolitical landscape is currently undergoing a seismic shift as emerging economies collectively challenge the hegemony of traditional Western financial institutions. Diplomatic correspondents note that this strategic realignment could inherently destabilize established trade corridors, prompting a comprehensive reevaluation of bilateral alliances.", "cefr_level": "C1", "lexile_score": 1150, "category": "News"},
        {"title": "Landmark Ruling on Digital Privacy", "text": "In a landmark ruling, the appellate court has overturned the controversial legislation regarding digital privacy rights. Legal scholars assert that this precedent-setting verdict will inherently redefine the parameters of corporate data extraction, compelling tech conglomerates to implement transparent, user-centric data sovereignty protocols.", "cefr_level": "C1", "lexile_score": 1150, "category": "News"},
        {"title": "The Threat of Deepfake Technology", "text": "The unprecedented proliferation of deepfake technology has prompted lawmakers to frantically draft preemptive regulatory frameworks. Cybersecurity analysts caution that without robust, algorithmic detection mechanisms mandated at the federal level, the integrity of upcoming democratic electoral processes could be severely compromised by synchronized disinformation campaigns.", "cefr_level": "C1", "lexile_score": 1150, "category": "News"},

        # Level C2 - Lexile 1350
        {"title": "A Kaleidoscopic Descent into Neurosis", "text": "The narrative eschews the comfort of a linear trajectory, opting instead for a kaleidoscopic descent into the protagonist’s neuroses. It is a labyrinthine exploration of human frailty, where every declarative sentence is heavily laden with irony. The author’s surgical precision in dissecting the banal hypocrisies of the bourgeois existence leaves the reader utterly bereft of sympathetic anchors.", "cefr_level": "C2", "lexile_score": 1350, "category": "Literature"},
        {"title": "Linguistic Agility and Pastoral Beauty", "text": "In a tour de force of linguistic agility, the poet juxtaposes the ephemeral beauty of the pastoral with the encroaching, metallic brutalism of the modern metropolis. The verse is remarkably densely packed with obscure mythological allusions, demanding a reader willing to excavate meaning from beneath layers of deliberate syntactic obfuscation and haunting, rhythmic cadence.", "cefr_level": "C2", "lexile_score": 1350, "category": "Literature"},
        {"title": "The Subjectivity of Objective Truth", "text": "The novel’s denouement is a masterstroke of deliberate ambiguity, utterly refusing to placate the reader with neatly tied thematic threads. Through a meticulous layering of unreliable narration and subtle shifts in focalization, the text forces a retroactive re-evaluation of every preceding interaction, revealing the inherent subjectivity of objective truth.", "cefr_level": "C2", "lexile_score": 1350, "category": "Literature"},
        {"title": "The Elegant Framework of String Theory", "text": "The intricate dance of string theory posits a universe fundamentally composed not of point-like particles, but of one-dimensional, vibrating energetic strings. To reconcile the apparent contradictions between general relativity and quantum mechanics, the framework inherently necessitates the existence of multiple extra spatial dimensions, elegantly curled into imperceptible Calabi-Yau manifolds.", "cefr_level": "C2", "lexile_score": 1350, "category": "Science"},
        {"title": "Bioethical Conundrums in Genome Editing", "text": "The advent of CRISPR-Cas9 genome editing has arguably catalyzed the most profound bioethical conundrum of the modern era. While its efficacy in eradicating deleterious monogenic diseases is unprecedented, the theoretical threshold for creating transgenic, 'designer' progeny necessitates rigorous, globally unified regulatory frameworks to preclude an era of unprecedented genetic stratification.", "cefr_level": "C2", "lexile_score": 1350, "category": "Science"},
        {"title": "The Thermodynamics of Black Holes", "text": "Delving into the thermodynamics of black holes reveals a paradoxical intersection of entropy and quantum mechanics, famously articulated by Hawking radiation. The implication that information might be irrevocably lost as a black hole evaporates strikes at the very heart of quantum determinism, instigating a fierce, ongoing theoretical battle regarding the fundamental conservation of information.", "cefr_level": "C2", "lexile_score": 1350, "category": "Science"},
        {"title": "The Combustible Milieu of the French Revolution", "text": "To attribute the outbreak of the French Revolution merely to an impoverished proletariat is a gross oversimplification of a highly combustible socio-political milieu. It was, rather, the volatile confluence of an inflexible, archaic absolutist monarchy, the proliferation of subversive Enlightenment philosophies, and a catastrophic fiscal crisis that inevitably ignited the powder keg of societal upheaval.", "cefr_level": "C2", "lexile_score": 1350, "category": "History"},
        {"title": "The Sophisticated Autocracy of Byzantium", "text": "The historiography surrounding the Byzantine Empire has long suffered from a Eurocentric bias that unfairly marginalized its pivotal role as a bastion of classical antiquity. Far from being a stagnant vestige of Rome, Byzantium was a dynamic, sophisticated autocracy that deftly navigated precarious geopolitical realities through a masterful amalgamation of shrewd diplomacy and formidable military stratagems.", "cefr_level": "C2", "lexile_score": 1350, "category": "History"},
        {"title": "Cultural Cross-Pollination on the Silk Road", "text": "The intricacies of the Silk Road transcended mere mercantile exchange; it was a sprawling, decentralized conduit for profound cross-cultural cross-pollination. The transmission of syncretic religious ideologies, paradigm-shifting technological innovations, and devastating epidemiological vectors along these arteries inextricably wove disparate civilizational destinies together long before the advent of modern globalization.", "cefr_level": "C2", "lexile_score": 1350, "category": "History"},
        {"title": "Volatility in the Macroeconomic Climate", "text": "The current macroeconomic climate is fraught with an unsettling degree of volatility, exacerbated by a confluence of hawkish central bank rhetoric and intractable supply chain bottlenecks. Pundits postulate that mitigating this stagflationary pressure requires a deft monetary touch, lest overly aggressive interest rate hikes inadvertently precipitate a protracted, systemic contraction of the global economy.", "cefr_level": "C2", "lexile_score": 1350, "category": "News"},
        {"title": "Diplomatic Deadlock at the Summit", "text": "The diplomatic summit concluded yesterday with a communique so replete with non-committal bureaucratic boilerplate that it essentially obfuscated the complete lack of tangible consensus. Behind closed doors, however, insiders report an atmosphere of palpable acrimony, suggesting that the underlying structural grievances between the participating hegemons remain wholly unresolved.", "cefr_level": "C2", "lexile_score": 1350, "category": "News"},
        {"title": "The Collapse of an Infrastructural Conglomerate", "text": "The precipitous collapse of the infrastructural conglomerate serves as a stark, cautionary tale regarding the perils of unchecked corporate hubris and obfuscated financial leveraging. Forensic auditors are currently unraveling a labyrinthine web of shell companies and creative accounting practices, forecasting a protracted legal quagmire that will likely ensnare multiple regulatory bodies in its wake.", "cefr_level": "C2", "lexile_score": 1350, "category": "News"}
    ]

    # Cleanup First: Delete all existing data
    passages_col.delete_many({})

    # Insert all 72 new passages
    if passages:
        result = passages_col.insert_many(passages)
        print(f"Successfully seeded {len(result.inserted_ids)} passages!")
    else:
        print("No passages to seed.")

if __name__ == "__main__":
    seed_passages()
